<a href="https://colab.research.google.com/github/zhouqic4/MSSP607-GitHub/blob/main/WeeklyModules/Week06/revised_week6_participation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
pd.options.display.max_rows = 20

In [ ]:
url = 'https://raw.githubusercontent.com/zhouqic4/MSSP607-GitHub/main/data/Student%20Performance%20Data.csv'
students = pd.read_csv(url)
print(students.shape)
students.head()

(1000, 10)

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect
0,female,group B,bachelor's degree,standard,72,72,74,218,none,medium
1,female,group C,some college,standard,69,90,88,247,completed,high
2,female,group B,master's degree,standard,90,95,93,278,none,high
3,male,group A,associate's degree,free/reduced,47,57,44,148,none,low
4,male,group C,some college,standard,76,78,75,229,none,high

In [ ]:
average = lambda x, y, z: (x + y + z) / 3
average(72, 90, 88)

83.33333333333333

In [ ]:
high_scorers= lambda df: df[df['total score'] >= 250]
top = high_scorers(students)
print(len(top), 'students scored 250 or more')
top.head()

139 students scored 250 or more

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect
2,female,group B,master's degree,standard,90,95,93,278,none,high
6,female,group B,some college,standard,88,95,92,275,completed,high
16,male,group C,high school,standard,88,89,86,263,none,high
34,male,group E,some college,standard,97,87,82,266,none,high
38,female,group D,associate's degree,free/reduced,75,90,88,253,completed,high

In [ ]:
score_table = lambda df: pd.DataFrame({
    'gender': df['gender'],
    'prep course': df['test preparation course'],
    'average score': (df['math score'] + df['reading score'] + df['writing score'])/3
})
scores = score_table(students)
scores.head()

   gender prep course  average score
0  female        none      72.666667
1  female   completed      82.333333
2  female        none      92.666667
3    male        none      49.333333
4    male        none      76.333333

In [ ]:
edu_to_level = {
  'some high school': 'high school',
  'high school': 'high school',
  'some college': 'college',
  "associate's degree": 'college',
  "bachelor's degree": 'college',
  "master's degree": 'graduate'
}

In [ ]:
scores['parent education'] = students['parental level of education'].map(lambda x: edu_to_level[x])
scores.head()

   gender prep course  average score parent education
0  female        none      72.666667          college
1  female   completed      82.333333          college
2  female        none      92.666667         graduate
3    male        none      49.333333          college
4    male        none      76.333333          college

In [ ]:
bins = [0, 60, 70, 80, 90, 101]
group_names = ['F', 'D', 'C', 'B', 'A']
get_grade = lambda df: pd.cut(df['average score'], bins, labels=group_names, right=False)
scores['grade'] = get_grade(scores)
scores.head()

   gender prep course  average score parent education grade
0  female        none      72.666667          college     C
1  female   completed      82.333333          college     B
2  female        none      92.666667         graduate     A
3    male        none      49.333333          college     F
4    male        none      76.333333          college     C

In [ ]:
scores['grade'].value_counts()

grade
F    285
C    261
D    256
B    146
A     52
Name: count, dtype: int64

In [ ]:
transform = lambda x: x.replace(' ', '_').upper()
scores.rename(columns=transform).head()

   GENDER PREP_COURSE  AVERAGE_SCORE PARENT_EDUCATION GRADE
0  female        none      72.666667          college     C
1  female   completed      82.333333          college     B
2  female        none      92.666667         graduate     A
3    male        none      49.333333          college     F
4    male        none      76.333333          college     C

In [ ]:
prep_summary = lambda df: df.groupby('test preparation course')['total score'].mean()
prep_summary(students)

test preparation course
completed    218.008380
none         195.116822
Name: total score, dtype: float64